Auth:
  license: "-c0AUaD78c6scKDAuP9_yXtLulQ00A23QY8mHciCzjJgP" # Your license key

System:
  name: "Hex Status" # Name of the service
  description: "Check real-time updates on the status of Hex Modz services," # Description of the service
  Port: 3000  # Port to run on
  refresh_interval: 60 # seconds
  pingInterval: 100 # seconds
  webhook_url: "https://discord.com/api/webhooks/1325197174815981598/G0-1GWkQuwtZOpUWPXrMaAoomksFWW0DEBex0A6yRizUR0hA-64MQfNSJ9RvofeyGSxl" # Webhook URL
  thumbnail: "https://hexmodz.com/assets/logo.png" # Thumbnail URL
  footer: "© 2024 - 2025 Hex Modz" 
  version: "4.0.0"

theme:
  primary: "#ff0000"  # Red
  secondary: "#000000" # Black
  accent: "#ff3333"  
  background: "#1a1a1a"

services:
  - name: "Website"
    url: "https://hexmodz.com"

  - name: "Hex Share"
    url: "https://share.hexmodz.com"

  - name: "Hex Auth (Dashboard)"
    url: "https://dash.hexmodz.com"

  - name: "Hex Auth (API)"
    url: "https://api.hexmodz.com"
