System:
  name: "Hex Status" # Name of the service
  description: "Check real-time updates on the status of Hex Modz services," # Description of the service
  Port: 3000  # Port to run on
  refresh_interval: 120 # seconds
  webhook_url: "" # Webhook URL
  thumbnail: ""  
  footer: "© 2024 - 2025 Hex Modz" 

theme:
  primary: "#ff0000"  # Red
  secondary: "#000000" # Black
  accent: "#ff3333"
  background: "#1a1a1a"

services:
  - name: "Website"
    type: "http"
    url: "https://hexmodz.com"
    port: 443

  - name: "Hex Share"
    type: "http"
    url: "https://share.hexmodz.com"
    port: 443

  - name: "Hex Auth (Dashboard)"
    type: "http"
    url: "https://dash.hexmodz.com"
    port: 443

  - name: "Hex Auth (API)"
    type: "http"
    url: "https://api.hexmodz.com"
    port: 443
